[package]
name = "mqtt-client"
version = "0.1.0"
edition = "2024"

[dependencies]
paho-mqtt = "0.13.3"
serde = { version = "1.0.219", features = ["derive"] }
serde_yaml = "0.9.34-deprecated"

[[bin]]
name = "sub"
path = "src/sub/main.rs"

[[bin]]
name = "pub"
path = "src/pub/main.rs"
